name: Publish Artifacts to Netlify

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Check source code
        uses: actions/checkout@v4
        with:
          repository: entropy-cloud/nop-entropy
          path: code

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build packages
        working-directory: code
        run: |
          echo "NOP_LATEST_COMMIT=$(git log --format="%H" -n 1)" >> ${GITHUB_ENV}
          mkdir -p ${GITHUB_WORKSPACE}/.m2/repository
          mvn -B \
            -Dmaven.repo.local=${GITHUB_WORKSPACE}/.m2/repository \
            -DskipTests -Dquarkus.package.type=fast-jar \
            --file pom.xml \
            clean install

      - name: Build IDEA plugin
        working-directory: nop-idea-plugin
        run: |
          bash ./gradlew buildPlugin

      - name: Copy artifacts
        run: |
          mkdir -p io/github
          cp code/nop-idea-plugin/build/distributions/nop-idea-plugin-*s.zip .
          rm -rf io/github/entropy-cloud
          cp -r .m2/repository/io/github/entropy-cloud io/github/

          for file in `find io/github -name maven-metadata-local.xml`; do
            mv $file $(echo $file | sed 's/-local//g')
          done

      - name: Commit artifacts
        run: |
          sed "s|%latest_commit%|${NOP_LATEST_COMMIT}|g" -i README.md
          git config user.name "$(git log --format='%an' HEAD^!)"
          git config user.email "$(git log --format='%ae' HEAD^!)"
          git add .
          git commit -m "Update artifacts"
          git push
