name: Publish Artifacts to Netlify

on:
  push:
    branches: ['master']
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Check source code
        uses: actions/checkout@v4
        with:
          repository: entropy-cloud/nop-entropy
          path: code
      - name: Check artifact repo
        uses: actions/checkout@v4
        with:
          repository: flytreeleft/nop-artifact-repo
          path: dist

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build packages
        working-directory: code
        run: |
          NOP_DIST_DIR="${GITHUB_WORKSPACE}/dist"
          NOP_LATEST_COMMIT="$(git log --format="%H" -n 1)"

          rm -rf ${NOP_DIST_DIR}/io/github/entropy-cloud || echo "Ignore"

          # 部署构建产物到本地指定目录
          # https://dzone.com/articles/using-github-as-maven-repository
          # https://stackoverflow.com/questions/12435283/adding-a-maven-distribution-repository-on-the-command-line#answer-39439854
          mvn -B \
            -DaltDeploymentRepository=internal::default::file://${NOP_DIST_DIR} \
            -DskipTests \
            -Dquarkus.package.type=uber-jar \
            --file pom.xml \
            clean deploy

          NOP_VERSION="$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
          NOP_CLI_JAR_PATH="$(cd ${NOP_DIST_DIR} && find io/github/entropy-cloud/nop-cli -name 'nop-cli-*.jar')"
          NOP_CLI_JAR_NAME="$(basename ${NOP_CLI_JAR_PATH})"

          sed "s|%version%|${NOP_VERSION}|g" -i ${NOP_DIST_DIR}/USAGE.md
          sed "s|%latest_commit%|${NOP_LATEST_COMMIT}|g" -i ${NOP_DIST_DIR}/USAGE.md
          sed "s|%cli_jar_path%|${NOP_CLI_JAR_PATH}|g" -i ${NOP_DIST_DIR}/USAGE.md
          sed "s|%cli_jar_name%|${NOP_CLI_JAR_NAME}|g" -i ${NOP_DIST_DIR}/USAGE.md

      - name: Build IDEA plugin
        working-directory: code/nop-idea-plugin
        run: |
          NOP_DIST_DIR="${GITHUB_WORKSPACE}/dist"

          rm -f ${NOP_DIST_DIR}/nop-idea-plugin-*.zip

          bash ./gradlew buildPlugin

          NOP_IDEA_PLUGIN_NAME="$(basename `ls build/distributions/nop-idea-plugin-*.zip`)"

          cp build/distributions/${NOP_IDEA_PLUGIN_NAME} ${NOP_DIST_DIR}/

          sed "s|%idea_plugin_name%|${NOP_IDEA_PLUGIN_NAME}|g" -i ${NOP_DIST_DIR}/USAGE.md

      - name: Commit artifacts
        working-directory: dist
        # Note：推送至当前仓库，需在仓库配置中启用 Action 的写权限
        run: |
          git config user.name "$(git log --format='%an' HEAD^!)"
          git config user.email "$(git log --format='%ae' HEAD^!)"

          git branch -D dist || echo "Ignore"
          git checkout -B dist
          git add .
          git commit -m "Update artifacts"
          git push origin dist -f
